# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_design.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(924, 651)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.zeichner_tab = QtWidgets.QWidget()
        self.zeichner_tab.setObjectName("zeichner_tab")
        self.pushButton = QtWidgets.QPushButton(self.zeichner_tab)
        self.pushButton.setGeometry(QtCore.QRect(780, 10, 111, 51))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.zeichner_tab)
        self.pushButton_2.setGeometry(QtCore.QRect(780, 70, 111, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.mapDrawing_graphicsView = QtWidgets.QGraphicsView(self.zeichner_tab)
        self.mapDrawing_graphicsView.setGeometry(QtCore.QRect(10, 10, 751, 521))
        self.mapDrawing_graphicsView.setMouseTracking(True)
        self.mapDrawing_graphicsView.setObjectName("mapDrawing_graphicsView")
        self.listWidget = QtWidgets.QListWidget(self.zeichner_tab)
        self.listWidget.setGeometry(QtCore.QRect(780, 130, 111, 91))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.tabWidget.addTab(self.zeichner_tab, "")
        self.animation_tab = QtWidgets.QWidget()
        self.animation_tab.setObjectName("animation_tab")
        self.animation_graphicsView = QtWidgets.QGraphicsView(self.animation_tab)
        self.animation_graphicsView.setGeometry(QtCore.QRect(10, 10, 881, 541))
        self.animation_graphicsView.setObjectName("animation_graphicsView")
        self.tabWidget.addTab(self.animation_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 924, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuTrafficSim_GUI = QtWidgets.QMenu(self.menuBar)
        self.menuTrafficSim_GUI.setObjectName("menuTrafficSim_GUI")
        self.menuBearbeiten = QtWidgets.QMenu(self.menuBar)
        self.menuBearbeiten.setObjectName("menuBearbeiten")
        self.menuHilfe = QtWidgets.QMenu(self.menuBar)
        self.menuHilfe.setObjectName("menuHilfe")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.action_ber_TrafficSim = QtWidgets.QAction(MainWindow)
        self.action_ber_TrafficSim.setObjectName("action_ber_TrafficSim")
        self.menuHilfe.addAction(self.action_ber_TrafficSim)
        self.menuBar.addAction(self.menuTrafficSim_GUI.menuAction())
        self.menuBar.addAction(self.menuBearbeiten.menuAction())
        self.menuBar.addAction(self.menuHilfe.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TrafficSim"))
        self.pushButton.setText(_translate("MainWindow", "Speichern"))
        self.pushButton_2.setText(_translate("MainWindow", "Laden"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Straße"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "Nicht Straße"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "Auto spawn"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.zeichner_tab), _translate("MainWindow", "Map Zeichner"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.animation_tab), _translate("MainWindow", "Animation"))
        self.menuTrafficSim_GUI.setTitle(_translate("MainWindow", "Datei"))
        self.menuBearbeiten.setTitle(_translate("MainWindow", "Bearbeiten"))
        self.menuHilfe.setTitle(_translate("MainWindow", "Hilfe"))
        self.action_ber_TrafficSim.setText(_translate("MainWindow", "Über TrafficSim"))

